import { TabWithItems } from '../../src/poe.types';
export const myfragments = {
	id: '05a436f120',
	index: 4,
	items: [
		{
			baseType: 'Abyss Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains an additional Abyss'],
			flavourText: ['They search forever for more souls to drag to the dark.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJBYnlzcyIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/5afc346c84/LesserScarabAbyss.png',
			id: '00d08984ce657a3238dfe877bceac34ddafbfbf448b7dd98fcbdfa7e8bb9a711',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['2', 0]] },
			],
			stackSize: 2,
			typeLine: 'Abyss Scarab',
			verified: false,
			w: 1,
			x: 208,
			y: 0,
		},
		{
			baseType: 'Sacrifice at Dusk',
			descrText: 'Can be used in a personal Map Device.',
			flavourText: ['The Vaal shall never fear the setting of our sun.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9WYWFsMDQiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/6c797c0f93/Vaal04.png',
			id: 'bb4bbee994a0d0cf50ee2487021e7e0d6501b02988c852b2d31cf93fc9d9174d',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/10', 0]] }],
			stackSize: 2,
			typeLine: 'Sacrifice at Dusk',
			verified: false,
			w: 1,
			x: 3,
			y: 0,
		},
		{
			baseType: 'Splinter of Tul',
			descrText: "Combine 100 Splinters to create Tul's Breachstone.",
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaFNoYXJkQ29sZCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/ef894cc215/BreachShardCold.png',
			id: '2dc6b92abae0a96cf7570b60c14ac06fc42a86bb11e9613acd7df5ff7b317a3b',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 100,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['2/100', 0]] }],
			stackSize: 2,
			typeLine: 'Splinter of Tul',
			verified: false,
			w: 1,
			x: 23,
			y: 0,
		},
		{
			baseType: 'Sacrifice at Dawn',
			descrText: 'Can be used in a personal Map Device.',
			flavourText: ['Only those who aspire can dare to hope.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9WYWFsMDIiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/2e0739455f/Vaal02.png',
			id: '2e0931bb95ba8a3af5e5a5f912ac61784ca9036124d48fc94e4e636092952bf4',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/10', 0]] }],
			stackSize: 1,
			typeLine: 'Sacrifice at Dawn',
			verified: false,
			w: 1,
			x: 1,
			y: 0,
		},
		{
			baseType: 'Ritual Scarab of Selectiveness',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: [
				'Rerolling Favours at Ritual Altars in Area has no cost the first 2 times\nRitual Altars in Area allow rerolling Favours 1 additional time',
			],
			flavourText: ['Pick and choose which sacred tenets you prefer...'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJSaXR1YWwiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/744a25b9f9/LesserScarabRitual.png',
			id: '734ac021f556ead8c71b9a1785b876284bbd30f9216f68184e7fb792f5b2aa35',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['2', 0]] },
			],
			stackSize: 1,
			typeLine: 'Ritual Scarab of Selectiveness',
			verified: false,
			w: 1,
			x: 223,
			y: 0,
		},
		{
			baseType: 'Splinter of Xoph',
			descrText: "Combine 100 Splinters to create Xoph's Breachstone.",
			frameType: 5,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvQnJlYWNoL0JyZWFjaFNoYXJkRmlyZSIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/c0deb5799d/BreachShardFire.png',
			id: 'bb9e74fca58eb9dc8b4aa08ebae732fb38f29ea802729f419b07dbc8eb110e99',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 100,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/100', 0]] }],
			stackSize: 1,
			typeLine: 'Splinter of Xoph',
			verified: false,
			w: 1,
			x: 22,
			y: 0,
		},
		{
			baseType: 'Betrayal Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains Jun'],
			flavourText: ['The Syndicate must pay for what they have done.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJCZXRyYXlhbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/26d3ff70f1/LesserScarabBetrayal.png',
			id: '5977090a370bd35d07270fa7be4e8258b87c4f9b6f91a41af0adb7e7b525a352',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Betrayal Scarab',
			verified: false,
			w: 1,
			x: 233,
			y: 0,
		},
		{
			baseType: 'Bestiary Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains Einhar'],
			flavourText: ['The Beastmaster answers the call.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJCZWFzdHMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/ea23afd0ff/LesserScarabBeasts.png',
			id: 'ab6641c1d34b385c69b45abb14b496c1636942dc5aa68626c250cfea928f6860',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Bestiary Scarab',
			verified: false,
			w: 1,
			x: 172,
			y: 0,
		},
		{
			baseType: 'Legion Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains an additional Legion Encounter'],
			flavourText: ['What good is peace to a warrior?'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJMZWdpb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/0006525c3c/LesserScarabLegion.png',
			id: 'ed08cdfbb971e12e479eedbd998c9f84cc38f759402ff534d1d016d55320b13e',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['4', 0]] },
			],
			stackSize: 1,
			typeLine: 'Legion Scarab',
			verified: false,
			w: 1,
			x: 203,
			y: 0,
		},
		{
			baseType: 'Divination Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['150% increased Divination Cards found in Area'],
			flavourText: ['Fate can be... encouraged.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJEaXZpbmF0aW9uIiwidyI6MSwiaCI6MSwic2NhbGUiOjF9XQ/ac84db8246/LesserScarabDivination.png',
			id: 'c3cc2ecbb3b30fb095c01e7d603880b1cb5f557da5ad1806211840209812de02',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['2', 0]] },
			],
			stackSize: 1,
			typeLine: 'Divination Scarab',
			verified: false,
			w: 1,
			x: 183,
			y: 0,
		},
		{
			baseType: 'Incursion Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains Alva'],
			flavourText: ['Uncover the secrets of the Vaal one incursion at a time.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJJbmN1cnNpb24iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/44cc3c3c34/LesserScarabIncursion.png',
			id: 'fdb3b7150c2911f5c5befd04fe3d4ec1bc3f32e24ecf362db4c1af8a08c034ff',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Incursion Scarab',
			verified: false,
			w: 1,
			x: 229,
			y: 0,
		},
		{
			baseType: 'Ultimatum Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains an Ultimatum Encounter'],
			flavourText: ['A challenge may be requested at any time.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJVbHRpbWF0dW0iLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/e0bf2875db/LesserScarabUltimatum.png',
			id: 'f10386312c9431176054341a457ce811e85792403db3ef998c01a0147c6bde0f',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Ultimatum Scarab',
			verified: false,
			w: 1,
			x: 242,
			y: 0,
		},
		{
			baseType: 'Influencing Scarab of the Elder',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Adds Elder Influence outcome to Area'],
			flavourText: ['Beyond the light lies only the void.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJFbGRlciIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/11cabe4d12/LesserScarabElder.png',
			id: '7b7063a75bf8d4adf3100152e77022272ad3f56334ba7441d2c136ec2da17fd1',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Influencing Scarab of the Elder',
			verified: false,
			w: 1,
			x: 177,
			y: 0,
		},
		{
			baseType: 'Breach Scarab',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['Area contains 2 additional Breaches'],
			flavourText: ['They are never far.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9MZXNzZXJTY2FyYWJCcmVhY2giLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/37bd40da6c/LesserScarabBreach.png',
			id: 'a9b200745c4d3060340f51031ae969b8575ca1c951aad8cb717a275c5221a481',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['4', 0]] },
			],
			stackSize: 1,
			typeLine: 'Breach Scarab',
			verified: false,
			w: 1,
			x: 159,
			y: 0,
		},
		{
			baseType: 'Betrayal Scarab of Intelligence',
			descrText: 'Can be used in a personal Map Device to add modifiers to a Map.',
			explicitMods: ['150% Increased Intelligence gained from\nImmortal Syndicate targets encountered in Area'],
			flavourText: ['Those that can never die fear only pain.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvQ3VycmVuY3kvU2NhcmFicy9Ob3JtYWxTY2FyYWJCZXRyYXlhbCIsInciOjEsImgiOjEsInNjYWxlIjoxfV0/01b158342c/NormalScarabBetrayal.png',
			id: '8dc858fc28407036c39928e9d4f5a5c9b994a69acc2c4602bcc7b4993ed77993',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [
				{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/20', 0]] },
				{ displayMode: 0, name: 'Limit', type: 87, values: [['1', 0]] },
			],
			stackSize: 1,
			typeLine: 'Betrayal Scarab of Intelligence',
			verified: false,
			w: 1,
			x: 234,
			y: 0,
		},
		{
			baseType: 'Sacrifice at Noon',
			descrText: 'Can be used in a personal Map Device.',
			flavourText: ['The light without pales in comparison to the light within.'],
			frameType: 0,
			h: 1,
			icon: 'https://web.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvTWFwcy9WYWFsMDMiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/85d03a6bbf/Vaal03.png',
			id: '007f946ab586eada7d4f8f10ecf1b90acf49ce688effed541997729f94a3dc98',
			identified: true,
			ilvl: 0,
			inventoryId: 'Stash1',
			league: 'Hardcore Necropolis',
			maxStackSize: 5000,
			name: '',
			properties: [{ displayMode: 0, name: 'Stack Size', type: 32, values: [['1/10', 0]] }],
			stackSize: 1,
			typeLine: 'Sacrifice at Noon',
			verified: false,
			w: 1,
			x: 2,
			y: 0,
		},
	],
	metadata: { colour: 'ffff99' },
	name: 'F',
	type: 'FragmentStash',
} satisfies TabWithItems;
